// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/6/2025, 2:32:26 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/Zaid/Desktop/Uvend-Registration/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Zaid/Desktop/Uvend-Registration/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Zaid/Desktop/Uvend-Registration/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Zaid/Desktop/Uvend-Registration/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Zaid/Desktop/Uvend-Registration/plugins/**/*.{js,ts,mjs}","C:/Users/Zaid/Desktop/Uvend-Registration/composables/**/*.{js,ts,mjs}","C:/Users/Zaid/Desktop/Uvend-Registration/utils/**/*.{js,ts,mjs}","C:/Users/Zaid/Desktop/Uvend-Registration/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Zaid/Desktop/Uvend-Registration/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Zaid/Desktop/Uvend-Registration/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Zaid/Desktop/Uvend-Registration/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;