// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/11/20, 18:39:16
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/Ross/OneDrive/Documents/UvendRegistrationfinal/Uvend-Registration/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ross/OneDrive/Documents/UvendRegistrationfinal/Uvend-Registration/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ross/OneDrive/Documents/UvendRegistrationfinal/Uvend-Registration/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ross/OneDrive/Documents/UvendRegistrationfinal/Uvend-Registration/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ross/OneDrive/Documents/UvendRegistrationfinal/Uvend-Registration/plugins/**/*.{js,ts,mjs}","C:/Users/Ross/OneDrive/Documents/UvendRegistrationfinal/Uvend-Registration/composables/**/*.{js,ts,mjs}","C:/Users/Ross/OneDrive/Documents/UvendRegistrationfinal/Uvend-Registration/utils/**/*.{js,ts,mjs}","C:/Users/Ross/OneDrive/Documents/UvendRegistrationfinal/Uvend-Registration/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ross/OneDrive/Documents/UvendRegistrationfinal/Uvend-Registration/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ross/OneDrive/Documents/UvendRegistrationfinal/Uvend-Registration/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ross/OneDrive/Documents/UvendRegistrationfinal/Uvend-Registration/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;